apiVersion: v1
kind: ConfigMap
metadata:
  name: wow-config
data:
  mongo_uri: "mongodb://mongo:27017/wowcapital"
  PLUGIN_MANIFESTS_DIR: "/app/backend/plugins/examples"
  INSTRUMENTS_FILE: "/app/backend/config/instruments.yaml"
  REDIS_URL: "redis://redis:6379/0"
  MD_WS_ENABLED: "1"
