version: "3.9"
services:
  api:
    build:
      context: ../..
      dockerfile: backend/Dockerfile.api
    environment:
      # Binance
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      # or provide via Docker secrets with *_FILE
      # - BINANCE_API_KEY_FILE=/run/secrets/binance_api_key
      # - BINANCE_API_SECRET_FILE=/run/secrets/binance_api_secret
      # Bybit
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      # - BYBIT_API_KEY_FILE=/run/secrets/bybit_api_key
      # - BYBIT_API_SECRET_FILE=/run/secrets/bybit_api_secret
      - BYBIT_TESTNET=${BYBIT_TESTNET:-0}
      - BYBIT_CATEGORY=${BYBIT_CATEGORY:-spot}
      # Kraken
      - KRAKEN_API_KEY=${KRAKEN_API_KEY}
      - KRAKEN_API_SECRET=${KRAKEN_API_SECRET}
      # - KRAKEN_API_KEY_FILE=/run/secrets/kraken_api_key
      # - KRAKEN_API_SECRET_FILE=/run/secrets/kraken_api_secret
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BINANCE_MODE=spot
      - EXCHANGES_ENABLED=${EXCHANGES_ENABLED:-binance}
      - INSTRUMENTS_FILE=backend/config/instruments.yaml
      - MD_WS_ENABLED=1
      - MONGO_URI=mongodb://mongo:27017/wowcapital
      - PLUGIN_MANIFESTS_DIR=backend/plugins/examples
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - qdrant
    command: uvicorn backend.api_gateway.app:app --host 0.0.0.0 --port 8080
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
